
package fr.afcepf.al30.stock.airbrass;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GestionStockIHMService", targetNamespace = "http://airbrass.stock.al30.afcepf.fr", wsdlLocation = "http://192.168.102.196:18080/AirBrass_StockWS/services/serviceStockIHM?wsdl")
public class GestionStockIHMService
    extends Service
{

    private final static URL GESTIONSTOCKIHMSERVICE_WSDL_LOCATION;
    private final static WebServiceException GESTIONSTOCKIHMSERVICE_EXCEPTION;
    private final static QName GESTIONSTOCKIHMSERVICE_QNAME = new QName("http://airbrass.stock.al30.afcepf.fr", "GestionStockIHMService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.102.196:18080/AirBrass_StockWS/services/serviceStockIHM?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GESTIONSTOCKIHMSERVICE_WSDL_LOCATION = url;
        GESTIONSTOCKIHMSERVICE_EXCEPTION = e;
    }

    public GestionStockIHMService() {
        super(__getWsdlLocation(), GESTIONSTOCKIHMSERVICE_QNAME);
    }

    public GestionStockIHMService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GESTIONSTOCKIHMSERVICE_QNAME, features);
    }

    public GestionStockIHMService(URL wsdlLocation) {
        super(wsdlLocation, GESTIONSTOCKIHMSERVICE_QNAME);
    }

    public GestionStockIHMService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GESTIONSTOCKIHMSERVICE_QNAME, features);
    }

    public GestionStockIHMService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionStockIHMService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StockIHM
     */
    @WebEndpoint(name = "GestionStockIHMPort")
    public StockIHM getGestionStockIHMPort() {
        return super.getPort(new QName("http://airbrass.stock.al30.afcepf.fr", "GestionStockIHMPort"), StockIHM.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StockIHM
     */
    @WebEndpoint(name = "GestionStockIHMPort")
    public StockIHM getGestionStockIHMPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://airbrass.stock.al30.afcepf.fr", "GestionStockIHMPort"), StockIHM.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GESTIONSTOCKIHMSERVICE_EXCEPTION!= null) {
            throw GESTIONSTOCKIHMSERVICE_EXCEPTION;
        }
        return GESTIONSTOCKIHMSERVICE_WSDL_LOCATION;
    }

}
