package orchestrateur.airbrass.al30.afcepf.fr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "AchatPortType", targetNamespace = "fr.afcepf.al30.airbrass.orchestrateur")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    fr.afcepf.al30.banque.ObjectFactory.class,
    fr.afcepf.al30.stock.airbrass.ObjectFactory.class,
    orchestrateur.airbrass.al30.afcepf.fr.ObjectFactory.class
})
@FunctionalInterface
public interface AchatPortType {

    /**
     *
     * @param payload
     * @return returns orchestrateur.airbrass.al30.afcepf.fr.AchatResponse
     */
    @WebMethod(action = "fr.afcepf.al30.airbrass.orchestrateur/process")
    @WebResult(name = "AchatResponse", targetNamespace = "fr.afcepf.al30.airbrass.orchestrateur", partName = "payload")
    public AchatResponse process(
            @WebParam(name = "AchatRequest", targetNamespace = "fr.afcepf.al30.airbrass.orchestrateur", partName = "payload") AchatRequest payload);

}
