
package orchestrateur.airbrass.al30.afcepf.fr;

import fr.afcepf.al30.airbrass.enums.WSDLLocation;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Achat", targetNamespace = "fr.afcepf.al30.airbrass.orchestrateur", wsdlLocation = WSDLLocation.ACHAT)
public class Achat
    extends Service
{
    private static final URL ACHAT_WSDL_LOCATION;
    private static final WebServiceException ACHAT_EXCEPTION;
    private static final QName ACHAT_QNAME = new QName("fr.afcepf.al30.airbrass.orchestrateur", "Achat");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(WSDLLocation.ACHAT);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACHAT_WSDL_LOCATION = url;
        ACHAT_EXCEPTION = e;
        
    }

    public Achat() {
        super(__getWsdlLocation(), ACHAT_QNAME);
    }

    public Achat(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACHAT_QNAME, features);
    }

    public Achat(URL wsdlLocation) {
        super(wsdlLocation, ACHAT_QNAME);
    }

    public Achat(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACHAT_QNAME, features);
    }

    public Achat(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Achat(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AchatPortType
     */
    @WebEndpoint(name = "AchatPort")
    public AchatPortType getAchatPort() {
        return super.getPort(new QName("fr.afcepf.al30.airbrass.orchestrateur", "AchatPort"), AchatPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AchatPortType
     */
    @WebEndpoint(name = "AchatPort")
    public AchatPortType getAchatPort(WebServiceFeature... features) {
        return super.getPort(new QName("fr.afcepf.al30.airbrass.orchestrateur", "AchatPort"), AchatPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACHAT_EXCEPTION!= null) {
            throw ACHAT_EXCEPTION;
        }
        return ACHAT_WSDL_LOCATION;
    }

}
