INSERT INTO  `bdd_airguitare_stock`.`fournisseur` (`adresseMail`,`libelle`,`telephone`,`adresse`) VALUES ('gibson@contact.com','Gibson','01 02 03 04 05','RUE BLAISE PASCAL');
INSERT INTO  `bdd_airguitare_stock`.`fournisseur` (`adresseMail`,`libelle`,`telephone`,`adresse`) VALUES ('fender@contact.com','Fender','01 45 78 04 54','ALLEE BLAISE CENDRARS');
INSERT INTO  `bdd_airguitare_stock`.`fournisseur` (`adresseMail`,`libelle`,`telephone`,`adresse`) VALUES ('ibanez@contact.com','Ibanez','01 02 45 04 54','ALLEE DE LA BISQUINE');
INSERT INTO  `bdd_airguitare_stock`.`fournisseur` (`adresseMail`,`libelle`,`telephone`,`adresse`) VALUES ('takamine@contact.com','Takamine','01 21 03 15 05','ALLEE BILLIE HOLIDAY');
INSERT INTO  `bdd_airguitare_stock`.`fournisseur` (`adresseMail`,`libelle`,`telephone`,`adresse`) VALUES ('lâg@contact.com','Lâg','01 02 03 45 05','CHEMIN BIGNON BAGUET');
INSERT INTO  `bdd_airguitare_stock`.`fournisseur` (`adresseMail`,`libelle`,`telephone`,`adresse`) VALUES ('bird@contact.com','Bird','01 89 03 04 45','ALLEE BERTHE MORISOT');
INSERT INTO  `bdd_airguitare_stock`.`fournisseur` (`adresseMail`,`libelle`,`telephone`,`adresse`) VALUES ('schecter@contact.com','Schecter','01 02 52 04 25','RUE DE LA BERTHAUDERIE');
INSERT INTO  `bdd_airguitare_stock`.`fournisseur` (`adresseMail`,`libelle`,`telephone`,`adresse`) VALUES ('eagletone@contact.com','Eagletone','01 78 44 04 44','CHEMIN DE BERT');
INSERT INTO  `bdd_airguitare_stock`.`fournisseur` (`adresseMail`,`libelle`,`telephone`,`adresse`) VALUES ('alhambra@contact.com','Alhambra','01 02 77 77 05','CHEMIN DE BERRIEN');
INSERT INTO  `bdd_airguitare_stock`.`fournisseur` (`adresseMail`,`libelle`,`telephone`,`adresse`) VALUES ('yamaha@contact.com1','Yamaha','01 77 77 04 77','CHEMINEMENT DE BERRIEN');
INSERT INTO  `bdd_airguitare_stock`.`fournisseur` (`adresseMail`,`libelle`,`telephone`,`adresse`) VALUES ('jm.forest@contact.com','JM Forest','01 88 03 88 05','CHEMIN DE BERREGAS');
INSERT INTO  `bdd_airguitare_stock`.`fournisseur` (`adresseMail`,`libelle`,`telephone`,`adresse`) VALUES ('cuenca@contact.com','Cuenca','01 02 99 04 99','RUE BERNARD PALISSY');
INSERT INTO  `bdd_airguitare_stock`.`fournisseur` (`adresseMail`,`libelle`,`telephone`,`adresse`) VALUES ('esteve@contact.com','Esteve','01 02 86 04 86','ALLEE DES BERNACHES');
INSERT INTO  `bdd_airguitare_stock`.`fournisseur` (`adresseMail`,`libelle`,`telephone`,`adresse`) VALUES ('epiphone@contact.com','Epiphone','01 02 23 04 23','IMPASSE DU BIGNON');
INSERT INTO  `bdd_airguitare_stock`.`fournisseur` (`adresseMail`,`libelle`,`telephone`,`adresse`) VALUES ('tobago@contact.com','Tobago','01 02 32 04 32','ALLEE BLANCHE EDWARDS');
INSERT INTO  `bdd_airguitare_stock`.`fournisseur` (`adresseMail`,`libelle`,`telephone`,`adresse`) VALUES ('AudioTechnica@contact.com','Audio Technica','01 02 32 04 32','ALLEE BLANCHE EDWARDS');
INSERT INTO  `bdd_airguitare_stock`.`fournisseur` (`adresseMail`,`libelle`,`telephone`,`adresse`) VALUES ('BEYERDYNAMIC@contact.com','BEYERDYNAMIC','01 02 32 04 32','ALLEE BLANCHE EDWARDS');
INSERT INTO  `bdd_airguitare_stock`.`fournisseur` (`adresseMail`,`libelle`,`telephone`,`adresse`) VALUES ('Wittner@contact.com','Wittner','01 02 32 04 32','ALLEE BLANCHE EDWARDS');

INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("PF1512 NT NATURAL","images/IBANEZ_Acoustique.JPG",179,"REF.001",3,5,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("TAM100 WHITE TOSIN ABASI","images/IBANEZ+TAM100.JPG",3500,"REF.002",3,3,0);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("G10-3Q-NT 3/4 NATURAL","images/IBANEZ_classique.JPG",127,"REF.004",3,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("STC1 RED","images/BIRD_STC1_RED.JPG",40,"REF.005",6,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("DG1 NOIRE","images/BIRD_DG1_BK.JPG",37,"REF.006",6,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("UK1S NL SOPRANO","images/BIRD_UK1S_NT.JPG",8,"REF.007",6,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("BLACKJACK SLS C 8EX ACTIVE SATIN BLACK","images/SCHECTER_S_BLASLSC8EXA-SBK.JPG",900,"REF.009",7,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("HELLRAISER C 8 BLACK CHERRY","images/SCHECTER_S_C-8HR-BCH.JPG",1100,"REF.010",7,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("HELLRAISER C 8 BLACK","images/SCHECTER_S_C-8HR-BLK.JPG",950,"REF.011",7,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("UK1S NL SOPRANO","images/BIRD+UK1S+BL.JPG",5,"REF.012",6,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("TENOR HAU'OLI","images/FMIC+0955630021.JPG",79,"REF.013",2,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("TENOR NOHEA","images/FMIC+0955640021.JPG",240,"REF.014",2,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("RON EMORY LOYALTY PARLOR SUNBURST","images/FENDER+0968551998.JPG",315,"REF.015",2,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("CP-100 PARLOR","images/FMIC+0961571021.JPG",100,"REF.016",2,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("MA 1 3/4 STEEL STRING GLOSS PINK","images/FMIC+096-3002-056.JPG",120,"REF.017",2,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("RG652FX GK PRESTIGE JAPON GALAXY BLACK ","images/IBANEZ_Japan.JPG",850,"REF.020",3,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("UK1S NL SOPRANO","images/BIRD_UK1S_NT.JPG",8,"REF.024",6,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("CG1 4/4 NATURELLE","images/BIRD_CG1_NL.JPG",25,"REF.025",6,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("JÓIA","images/EAGLETONE+JOIA.JPG",240,"REF.029",8,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("HELLRAISER C 8 BLACK","images/SCHECTER_S_C-8HR-BLK.JPG",230,"REF.030",9,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("D'ETUDE CGS102 1/2","images/YAMAHA+CGS102.JPG",110,"REF.031",10,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("STUDENT 4/4","images/JMFSTUDENT44.JPG",179,"REF.032",11,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("TH5C HIRADE NATURAL GLOSS","images/GTV-TH5C.JPG",1200,"REF.033",4,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("GAUCHER 10-L CEDRE","images/GCU+10+L.JPG",250,"REF.034",12,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("OCCITANIA 300 RED CEDRE","images/GLAOC300.JPG",325,"REF.035",5,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("4ST SATIN","images/ESTEVE+15424SAT.JPG",350,"REF.036",13,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("1.4ST","images/ESTEVE+1-4ST.JPG",330,"REF.037",13,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("RAVEN NOIRE","images/EAGLETONE+RAVEN.JPG",130,"REF.038",8,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("SOUTH STATE C100 MATT GREY","images/EAGLETONE+SOUTH+STATE+C100+GRISE+MATE.JPG",120,"REF.039",8,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("STC1L SUNBURST - GAUCHER","images/BIRD+STC1L+SUNBURST.JPG",60,"REF.040",6,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("LES PAUL T TRADITIONAL 2017 ","images/GBI+LPTD17A6NH1.JPG",1700,"REF.041",1,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("SG STANDARD REISSUE STOPBAR","images/SGSR3VOFCNH1.JPG",2800,"REF.042",1,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("FLYING V T 2017 ALPINE WHITE","images/GBI+DSV17AWCH1.JPG",1000,"REF.043",1,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("FLYING V T 2017 EBONY","images/GBI+DSV17EBCH1.JPG",850,"REF.044",1,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("1974 LES PAUL CUSTOM REISSUE ","images/GIBSON+LPC74VOEBGH1.JPG",4500,"REF.045",1,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("GAUCHER LES PAUL TRADITIONAL","images/GBI+LPTD17LHBNH1.JPG",1700,"REF.046",1,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("DELUXE 20 B","images/EAGLETONE+DELUXE+20B.JPG",30,"REF.047",8,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("DELUXE 30 CL","images/EAGLETONE+DELUXE+30CL.JPG",30,"REF.048",8,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("ETUI POUR EPIPHONE LES PAUL","images/940-ENLPCS.JPG",129,"REF.049",14,3,3);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("HOUSSE GUITARE NOIRE SERIE 20","images/SERIE20.JPG",10,"REF.050",15,3,3);

INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("AT4080","images/AT4080.JPG",750,"REF.051",16,3,5);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("AT4081","images/AT+4081+AUDIO+TECHNICA+MICRO+STUDIO.JPG",580,"REF.052",16,3,5);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("M160","images/BEYER+M160.JPG",470,"REF.053",17,3,5);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("TG V90R","images/BEYER+TGV90R.JPG",360,"REF.054",17,3,5);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("CS N - TENSION NORMALE","images/EAGLETONE+CS+N.JPG",1,"REF.055",8,3,5);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("CSHQ H - TENSION FORTE","images/EAGLETONE+CSHQ+H.JPG",2,"REF.056",8,3,5);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("SAM BUSH SIG. MANDOLIN","images/GIBSON+SMG+SBS.JPG",8,"REF.057",1,3,5);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("IMDS4","images/IMDS4.JPG",3,"REF.058",3,3,5);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("MANDOLINE NICKLE PLATED STEEL","images/FMIC+0732250403.JPG",12,"REF.059",2,3,5);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("CELPICK 12","images/EAGLETONE+CELPICK12.JPG",2,"REF.060",8,3,5);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("MEDIATOR ECAILLE HEAVY","images/FENDER+ECAILLE+HEAVY.JPG",25,"REF.061",2,3,5);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("MEDIATOR ECAILLE MEDIUM","images/FMIC+0980351300.JPG",25,"REF.062",2,3,5);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("BOITE METAL 50 MEDIATORS - CALIBRE DUR","images/MEDIATORS-GIBSON-BOITE-50.JPG",9,"REF.063",1,3,5);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("FT1000 - ACCORDEUR METRONOME","images/EAGLETONE+FT1000.JPG",17,"REF.064",8,3,5);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("MT1000 - ACCORDEUR METRONOME","images/EAGLETONE+MT1000.JPG",12,"REF.065",8,3,5);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("FCT-12 ACCORDEUR CHROMATIQUE","images/FMIC+0239978100.JPG",11,"REF.066",2,3,5);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("DIAPASON","images/K&M+1680000001+TUNING+FORK.JPG",1,"REF.067",16,3,5);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("MM100","images/EAGLETONE+MM100.JPG",24,"REF.068",8,3,5);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("TAKTELL PICCOLO VIOLET PAILLEtTE","images/WITTNER+TAKTELL+PICCOLO+VIOLET.JPG",37,"REF.069",18,3,5);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("808M CHENE MAT","images/WITTNER+808M.JPG",89,"REF.070",18,3,5);
INSERT INTO  `bdd_airguitare_stock`.`produit` (`intitule`,`photo`,`prix_fournisseur`,`ref_produit`,`fournisseur_id`,`seuil`,`stock`) VALUES ("TAKTELL PICCOLO ROUGE RUBIS","images/WITTNER+TAKTELL+PICCOLO+RUBIS.JPG",37,"REF.071",18,3,5);


INSERT INTO  `bdd_airguitare_stock`.`utilisateur` (`login`,`password`,`name`) VALUES ('manager','afcepf','Manager');

INSERT INTO  `bdd_airguitare_stock`.`commande` (`date`,`statut`,`user_id`,`intitule`) VALUES ('2017/04/12','Reception',1,"CMD 001");
INSERT INTO  `bdd_airguitare_stock`.`commande` (`date`,`statut`,`user_id`,`intitule`) VALUES ('2017/01/12','Reception',1,"CMD 002");
INSERT INTO  `bdd_airguitare_stock`.`commande` (`date`,`statut`,`user_id`,`intitule`) VALUES ('2017/02/12','Reception',1,"CMD 003");
INSERT INTO  `bdd_airguitare_stock`.`commande` (`date`,`statut`,`user_id`,`intitule`) VALUES ('2017/04/20','En cours',1,"CMD 004");

INSERT INTO  `bdd_airguitare_stock`.`ligne_commande` (`quantite`,`commande_id`,`produit_id`) VALUES (2,1,1);
INSERT INTO  `bdd_airguitare_stock`.`ligne_commande` (`quantite`,`commande_id`,`produit_id`) VALUES (8,1,20);
INSERT INTO  `bdd_airguitare_stock`.`ligne_commande` (`quantite`,`commande_id`,`produit_id`) VALUES (10,1,18);
INSERT INTO  `bdd_airguitare_stock`.`ligne_commande` (`quantite`,`commande_id`,`produit_id`) VALUES (5,1,17);
INSERT INTO  `bdd_airguitare_stock`.`ligne_commande` (`quantite`,`commande_id`,`produit_id`) VALUES (7,1,35);
INSERT INTO  `bdd_airguitare_stock`.`ligne_commande` (`quantite`,`commande_id`,`produit_id`) VALUES (2,2,4);
INSERT INTO  `bdd_airguitare_stock`.`ligne_commande` (`quantite`,`commande_id`,`produit_id`) VALUES (4,2,26);
INSERT INTO  `bdd_airguitare_stock`.`ligne_commande` (`quantite`,`commande_id`,`produit_id`) VALUES (8,2,14);
INSERT INTO  `bdd_airguitare_stock`.`ligne_commande` (`quantite`,`commande_id`,`produit_id`) VALUES (12,2,7);
INSERT INTO  `bdd_airguitare_stock`.`ligne_commande` (`quantite`,`commande_id`,`produit_id`) VALUES (15,2,6);
INSERT INTO  `bdd_airguitare_stock`.`ligne_commande` (`quantite`,`commande_id`,`produit_id`) VALUES (18,2,23);
INSERT INTO  `bdd_airguitare_stock`.`ligne_commande` (`quantite`,`commande_id`,`produit_id`) VALUES (50,3,18);
INSERT INTO  `bdd_airguitare_stock`.`ligne_commande` (`quantite`,`commande_id`,`produit_id`) VALUES (22,3,12);
INSERT INTO  `bdd_airguitare_stock`.`ligne_commande` (`quantite`,`commande_id`,`produit_id`) VALUES (12,3,22);
INSERT INTO  `bdd_airguitare_stock`.`ligne_commande` (`quantite`,`commande_id`,`produit_id`) VALUES (32,3,14);
INSERT INTO  `bdd_airguitare_stock`.`ligne_commande` (`quantite`,`commande_id`,`produit_id`) VALUES (23,3,13);
INSERT INTO  `bdd_airguitare_stock`.`ligne_commande` (`quantite`,`commande_id`,`produit_id`) VALUES (4,4,8);
INSERT INTO  `bdd_airguitare_stock`.`ligne_commande` (`quantite`,`commande_id`,`produit_id`) VALUES (6,4,19);
INSERT INTO  `bdd_airguitare_stock`.`ligne_commande` (`quantite`,`commande_id`,`produit_id`) VALUES (9,4,23);
INSERT INTO  `bdd_airguitare_stock`.`ligne_commande` (`quantite`,`commande_id`,`produit_id`) VALUES (12,4,36);