
package fr.afcepf.al30.formations;

import fr.afcepf.al30.airbrass.enums.WSDLLocation;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "serviceFormation", targetNamespace = "http://formations.al30.afcepf.fr", wsdlLocation = WSDLLocation.FORMATION)
public class ServiceFormation_Service
    extends Service
{

    private final static URL SERVICEFORMATION_WSDL_LOCATION;
    private final static WebServiceException SERVICEFORMATION_EXCEPTION;
    private final static QName SERVICEFORMATION_QNAME = new QName("http://formations.al30.afcepf.fr", "serviceFormation");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(WSDLLocation.FORMATION);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEFORMATION_WSDL_LOCATION = url;
        SERVICEFORMATION_EXCEPTION = e;
    }

    public ServiceFormation_Service() {
        super(__getWsdlLocation(), SERVICEFORMATION_QNAME);
    }

    public ServiceFormation_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEFORMATION_QNAME, features);
    }

    public ServiceFormation_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICEFORMATION_QNAME);
    }

    public ServiceFormation_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEFORMATION_QNAME, features);
    }

    public ServiceFormation_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceFormation_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceFormation
     */
    @WebEndpoint(name = "formport")
    public ServiceFormation getFormport() {
        return super.getPort(new QName("http://formations.al30.afcepf.fr", "formport"), ServiceFormation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceFormation
     */
    @WebEndpoint(name = "formport")
    public ServiceFormation getFormport(WebServiceFeature... features) {
        return super.getPort(new QName("http://formations.al30.afcepf.fr", "formport"), ServiceFormation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEFORMATION_EXCEPTION!= null) {
            throw SERVICEFORMATION_EXCEPTION;
        }
        return SERVICEFORMATION_WSDL_LOCATION;
    }

}
